#!/bin/bash

protected_branches=("master" "develop" "test")
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for branch in "${protected_branches[@]}"; do
	if [ $branch = $current_branch ]; then
		# Exit with error to avoid push
		echo "Branch '$current_branch' protected!"
		exit 1
	fi
done
